global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'seta-api'
    metrics_path: '/api/telemetry/prometheus'
    static_configs:
      - targets: ['nginx-proxy:8080']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
